services:
  netmeter:
    container_name: netmeter
    image: ghcr.io/neflalabs/netmeter:latest
    restart: unless-stopped
    ports:
      - "80:3000"
    volumes:
      - netmeter_db:/app/data
    environment:
      - DATABASE_URL=file:/app/data/netmeter.db
      - NODE_ENV=production
    env_file: .env
    healthcheck:
      test: ["CMD", "bun", "-e", "fetch('http://localhost:3000/health').then(r => r.ok ? process.exit(0) : process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  netmeter_db: