PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_settings` (
	`singleton` integer PRIMARY KEY DEFAULT 1 NOT NULL,
	`monthly_fee` integer DEFAULT 0 NOT NULL,
	`admin_phone_number` text DEFAULT '' NOT NULL,
	`app_title` text DEFAULT 'NetMeter',
	`app_subtitle` text DEFAULT 'Cara baru patungan WiFi',
	`app_url` text DEFAULT '',
	`listing_per_home` integer DEFAULT 6 NOT NULL,
	`announcement_title` text DEFAULT 'Pengumuman',
	`announcement_message` text DEFAULT '',
	`announcement_type` text DEFAULT 'INFO',
	`announcement_active` integer DEFAULT false,
	`announcement_created_at` integer,
	`announcement_updated_at` integer,
	`bill_template` text DEFAULT 'Assalamualaikum {name}, patungan bulan {month} / {year} sebesar Rp. {amount} sudah bisa dibayar.{br} Untuk membayar secara otomatis, klik di sini: {link} {br}{br} _Pesan ini dikirim otomatis oleh aplikasi._',
	`payment_template` text DEFAULT 'Assalamualaikum {name}, patungan sebesar Rp. {amount} via {method} sudah diterima. detailnya bisa cek disini : {link} {br} Maturnuwun! {br}{br} _Pesan ini dikirim otomatis oleh aplikasi._',
	`reminder_template` text DEFAULT 'Assalamualaikum {name}, sekadar mengingatkan patungan WiFi bulan {month} / {year} sebesar Rp. {amount} belum lunas. Jika sudah bayar, abaikan pesan ini: {link} {br}{br} _Pesan ini dikirim otomatis oleh aplikasi._',
	`global_due_day` integer DEFAULT 10,
	`global_reminder_interval` integer DEFAULT 3,
	`wa_enabled` integer DEFAULT false,
	`wa_service_url` text DEFAULT 'http://localhost:3030/api/v1',
	`wa_api_key` text DEFAULT '',
	`wa_instance_id` text DEFAULT '',
	`wa_webhook_secret` text DEFAULT '',
	`auto_notify_new_bill` integer DEFAULT false,
	`auto_notify_payment_success` integer DEFAULT false,
	`auto_reminder_enabled` integer DEFAULT false,
	`reminder_time` text DEFAULT '09:00',
	`auto_bill_time` text DEFAULT '09:00',
	`quiet_hours_start` text DEFAULT '21:00',
	`quiet_hours_end` text DEFAULT '08:00',
	`quiet_hours_weekend` integer DEFAULT true,
	`manual_payment_enabled` integer DEFAULT true,
	`qris_payment_enabled` integer DEFAULT false,
	`manual_payment_details` text DEFAULT 'Tidak ingin menggunakan pembayaran otomatis? Silakan lakukan pembayaran tunai dengan menghubungi admin.',
	`qris_raw_string` text DEFAULT '00020101021126610014COM.GO-JEK.WWW01189360091439280284540210G9280284540303UMI51440014ID.CO.QRIS.WWW0215ID10253777680290303UMI5204553353033605802ID5910NEFLA LABS6006SORONG61059844562070703A0163044598',
	`midtrans_enabled` integer DEFAULT false,
	`midtrans_server_key` text,
	`midtrans_client_key` text,
	`midtrans_environment` text DEFAULT 'sandbox',
	`xendit_enabled` integer DEFAULT false,
	`xendit_secret_key` text,
	`xendit_verification_token` text,
	`xendit_environment` text DEFAULT 'sandbox',
	`updated_at` integer
);
--> statement-breakpoint
INSERT INTO `__new_settings`("singleton", "monthly_fee", "admin_phone_number", "app_title", "app_subtitle", "app_url", "listing_per_home", "announcement_title", "announcement_message", "announcement_type", "announcement_active", "announcement_created_at", "announcement_updated_at", "bill_template", "payment_template", "reminder_template", "global_due_day", "global_reminder_interval", "wa_enabled", "wa_service_url", "wa_api_key", "wa_instance_id", "wa_webhook_secret", "auto_notify_new_bill", "auto_notify_payment_success", "auto_reminder_enabled", "reminder_time", "auto_bill_time", "quiet_hours_start", "quiet_hours_end", "quiet_hours_weekend", "manual_payment_enabled", "qris_payment_enabled", "manual_payment_details", "qris_raw_string", "midtrans_enabled", "midtrans_server_key", "midtrans_client_key", "midtrans_environment", "xendit_enabled", "xendit_secret_key", "xendit_verification_token", "xendit_environment", "updated_at") SELECT "singleton", "monthly_fee", "admin_phone_number", "app_title", "app_subtitle", "app_url", "listing_per_home", "announcement_title", "announcement_message", "announcement_type", "announcement_active", "announcement_created_at", "announcement_updated_at", "bill_template", "payment_template", "reminder_template", "global_due_day", "global_reminder_interval", "wa_enabled", "wa_service_url", "wa_api_key", "wa_instance_id", "wa_webhook_secret", "auto_notify_new_bill", "auto_notify_payment_success", "auto_reminder_enabled", "reminder_time", "auto_bill_time", "quiet_hours_start", "quiet_hours_end", "quiet_hours_weekend", "manual_payment_enabled", "qris_payment_enabled", "manual_payment_details", "qris_raw_string", "midtrans_enabled", "midtrans_server_key", "midtrans_client_key", "midtrans_environment", "xendit_enabled", "xendit_secret_key", "xendit_verification_token", "xendit_environment", "updated_at" FROM `settings`;--> statement-breakpoint
DROP TABLE `settings`;--> statement-breakpoint
ALTER TABLE `__new_settings` RENAME TO `settings`;--> statement-breakpoint
PRAGMA foreign_keys=ON;